contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #transmembrane channel"
    url: https://nfcore.slack.com/channels/transmembrane
    about: Discussion about the nf-core/transmembrane pipeline
